// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONdDyE7C6IRxY-9-E6mIsRUAgM-DTUF4',
    appId: '1:266833017891:web:154801b991203a521a0596',
    messagingSenderId: '266833017891',
    projectId: 'parking-management-23725',
    authDomain: 'parking-management-23725.firebaseapp.com',
    storageBucket: 'parking-management-23725.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZOwS9bMnEuHOV_JdIvw8u2EfVmbDOmI',
    appId: '1:266833017891:android:39e31c684ea1ef241a0596',
    messagingSenderId: '266833017891',
    projectId: 'parking-management-23725',
    storageBucket: 'parking-management-23725.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2BqmWt8sECliPANbu4yh8rhswrLWaSQA',
    appId: '1:266833017891:ios:07a417b1ea2aafab1a0596',
    messagingSenderId: '266833017891',
    projectId: 'parking-management-23725',
    storageBucket: 'parking-management-23725.firebasestorage.app',
    iosBundleId: 'com.example.parkingManagement',
  );
}
